I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 145, in script call
    call episode2 from _call_episode2
  File "game/episode 2.rpy", line 84, in script
    show screen info_box("1. TEXT TYPE: str") with dissolve
renpy.display.screen.ScreenNotFound: Screen 'info_box' is not known.

-- Full Traceback ------------------------------------------------------------

Traceback (most recent call last):
  File "game/script.rpy", line 145, in script call
    call episode2 from _call_episode2
  File "game/episode 2.rpy", line 84, in script
    show screen info_box("1. TEXT TYPE: str") with dissolve
  File "renpy/ast.py", line 2231, in execute
    self.call("execute")
    ~~~~~~~~~^^^^^^^^^^^
  File "renpy/ast.py", line 2195, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/statements.py", line 379, in call
    return method(parsed, *args, **kwargs)
           ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/common/000statements.rpy", line 671, in execute_show_screen
    renpy.show_screen(name, *args, **kwargs)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/screen.py", line 1355, in show_screen
    raise ScreenNotFound(name[0])
renpy.display.screen.ScreenNotFound: Screen 'info_box' is not known.

Windows-11-10.0.22621-SP0 AMD64
Ren'Py 8.4.1.25072401
Codebound 1.0
Wed Oct 29 15:44:40 2025
